# Site settings
title: asdf
header-img: img/home-bg.png
email: spetluri.1@gmail.com
copyright_name: spetluri
description: > # this means to ignore newlines until "baseurl:"
  asdf
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  spetluri
learn_profile: spetluri
email_username: spetluri.1@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
